openapi: 3.0.1
info:
  title: Stat service API
  version: v0
servers:
- description: Generated server url
  url: http://localhost:9090
tags:
- description: API для работы со статистикой посещений
  name: StatsController
paths:
  /hit:
    post:
      description: "Сохранение информации о том, что на uri конкретного сервиса бы\
        л отправлен запрос пользователем. Название сервиса, uri и ip пользователя\
        \ указаны в теле запроса."
      operationId: hit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointHit'
        description: данные запроса
        required: true
      responses:
        "201":
          description: Информация сохранена
      summary: "Сохранение информации о том, что к эндпоинту был запрос"
      tags:
      - StatsController
      x-content-type: application/json
      x-accepts:
      - application/json
  /stats:
    get:
      operationId: getStats
      parameters:
      - description: Дата и время начала диапазона за который нужно выгрузить статистику
          (в формате "yyyy-MM-dd HH:mm:ss")
        explode: true
        in: query
        name: start
        required: true
        schema:
          type: string
        style: form
      - description: Дата и время конца диапазона за который нужно выгрузить статистику
          (в формате "yyyy-MM-dd HH:mm:ss")
        explode: true
        in: query
        name: end
        required: true
        schema:
          type: string
        style: form
      - description: Список uri для которых нужно выгрузить статистику
        explode: true
        in: query
        name: uris
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Нужно ли учитывать только уникальные посещения (только с уникальным
          ip)
        explode: true
        in: query
        name: unique
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ViewStats'
                type: array
          description: Статистика собрана
      summary: "Получение статистики по посещениям. Обратите внимание: значение да\
        ты и времени нужно закодировать (например используя java.net.URLEncoder.encode) "
      tags:
      - StatsController
      x-accepts:
      - application/json
components:
  schemas:
    EndpointHit:
      example:
        app: ewm-main-service
        ip: 192.163.0.1
        id: 1
        uri: /events/1
        timestamp: 2022-09-06 11:00:23
      properties:
        id:
          description: Идентификатор записи
          example: 1
          format: int64
          readOnly: true
          type: integer
        app:
          description: Идентификатор сервиса для которого записывается информация
          example: ewm-main-service
          type: string
        uri:
          description: URI для которого был осуществлен запрос
          example: /events/1
          type: string
        ip:
          description: "IP-адрес пользователя, осуществившего запрос"
          example: 192.163.0.1
          type: string
        timestamp:
          description: "Дата и время, когда был совершен запрос к эндпоинту (в фор\
            мате \"yyyy-MM-dd HH:mm:ss\")"
          example: 2022-09-06 11:00:23
          type: string
      type: object
    ViewStats:
      example:
        app: ewm-main-service
        hits: 6
        uri: /events/1
      properties:
        app:
          description: Название сервиса
          example: ewm-main-service
          type: string
        uri:
          description: URI сервиса
          example: /events/1
          type: string
        hits:
          description: Количество просмотров
          example: 6
          format: int64
          type: integer
      type: object

