CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
    id  BIGSERIAL PRIMARY KEY,
    lat DECIMAL(9,6) NOT NULL,
    lon DECIMAL(9,6) NOT NULL
);

CREATE TABLE IF NOT EXISTS events(
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    annotation TEXT,
    description TEXT,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid BOOLEAN DEFAULT false,
    participant_limit BIGINT NOT NULL DEFAULT 0,
    request_moderation BOOLEAN DEFAULT true,
    state TEXT NOT NULL,

    CONSTRAINT fk_events_categories
        FOREIGN KEY(category_id) REFERENCES categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_events_locations
        FOREIGN KEY(location_id) REFERENCES locations(id)
);

CREATE TABLE IF NOT EXISTS compilations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT false,
    title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilation_event(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_event_compilation FOREIGN KEY(compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_event_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE
);